[package]
name = "evm-lens-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Fast EVM bytecode disassembler library"
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[dependencies]
hex.workspace = true
revm.workspace = true
lru.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
async-trait.workspace = true
thiserror.workspace = true
log.workspace = true
dirs.workspace = true
color-eyre.workspace = true

[dev-dependencies]
mockito.workspace = true
serde_json.workspace = true
tempfile.workspace = true
